"""Mechanism analysis: the flood boundary in (capacity x mix ratio) space.

Reads the phase-diagram manifests (r6 vision CNN, r6-state kinematic MLP,
r7 contact-rich MuJoCo MLP) and writes:

  results/figs/fig_phase_diagram.png   final success vs mix ratio, per
                                       capacity, one panel per regime
  results/mechanism.json               machine-readable boundary numbers

Usage:
    python scripts/analyze_mechanism.py
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

COLORS = {"cap32": "#1f77b4", "cap96": "#ff7f0e", "cap128": "#2ca02c"}
RATIO_ORDER = (0.25, 0.5, 1.0)
STYLE = {"relabel": "o--", "relabel_curated": "s-", "relabel_adaptive": "^-"}
UNBOUNDED = 8.0  # nominal mix ratio of blind relabeling (measured 3-8.5x)


def _final_success(cells: dict, label: str, name: str) -> float:
    for k, c in cells.items():
        if k != label:
            continue
        for sname, d in c["strategies"].items():
            if sname == name:
                return d["success_rate_mean"][-1]
    return float("nan")


def _final_at(cells: dict, cap: str, name: str, ratio=None) -> float:
    if name == "relabel_mix" and ratio is not None:
        return _final_success(cells, f"{cap}/mix{ratio:g}", name)
    return _final_success(cells, f"{cap}/{name}", name)


def load_manifest(path: Path) -> dict | None:
    if path.exists():
        return json.loads(path.read_text())
    return None


def main() -> None:
    vision = load_manifest(Path("results_v3/vision_r6/manifest.json"))
    contact = load_manifest(Path("results_contact/state/manifest.json"))
    state = load_manifest(Path("results_mech/state/manifest.json"))
    out: dict = {"vision": {}, "contact": {}, "state": {}}

    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.6), sharey=True)

    def plot_panel(ax, cells, caps, title, key):
        for cap in caps:
            # mix-ratio sweep (the controlled variable)
            xs, ys = [], []
            for r in RATIO_ORDER:
                ys.append(_final_at(cells, cap, "relabel_mix", ratio=r))
                xs.append(r)
            # blind relabeling at its measured unbounded mix ratio
            ys.append(_final_at(cells, cap, "relabel"))
            xs.append(UNBOUNDED)
            ax.plot(xs, ys, marker="o", lw=1.8, color=COLORS[cap],
                    label=f"capacity {cap[3:]}")
            out[key][cap] = {"ratios": list(RATIO_ORDER) + ["unbounded"],
                             "final_success": ys}
        ax.set_xscale("log")
        ax.set_xticks(list(RATIO_ORDER) + [UNBOUNDED])
        ax.set_xticklabels(["0.25x", "0.5x", "1x", "unbounded"], fontsize=8)
        ax.set_title(title, fontsize=10)
        ax.set_xlabel("relabeled:clean mix ratio (log)")
        ax.grid(alpha=0.3)
        ax.legend(frameon=False, fontsize=7)

    if vision:
        plot_panel(axes[0], vision["cells"], ("cap32", "cap128"),
                   "perception (CNN): the flood boundary", "vision")
    if state:
        plot_panel(axes[1], state["cells"], ("cap32", "cap96"),
                   "kinematic MLP: flood-robust", "state")
    if contact:
        plot_panel(axes[2], contact["cells"], ("cap32", "cap96"),
                   "contact-rich MLP (MuJoCo): flood-robust", "contact")

    axes[0].set_ylabel("final held-out success")

    # adaptive controller trace (vision, if present)
    ax_inset = None
    if vision:
        ax_inset = fig.add_axes([0.03, 0.52, 0.18, 0.38])
        for cap in ("cap32", "cap128"):
            for label, c in vision["cells"].items():
                if not label.startswith(cap) or "/relabel_adaptive" not in label:
                    continue
                for sname, d in c["strategies"].items():
                    log = d.get("curation_log") or []
                    ratios = [x.get("controller_ratio") for x in log]
                    ax_inset.plot(range(1, len(ratios) + 1), ratios, marker="o",
                                  ms=3, color=COLORS[cap],
                                  label=f"cap{cap[3:]}")
        ax_inset.set_title("adaptive ratio", fontsize=8)
        ax_inset.set_xlabel("iteration", fontsize=7)
        ax_inset.set_ylabel("controller ratio", fontsize=7)
        ax_inset.legend(frameon=False, fontsize=6)
        ax_inset.grid(alpha=0.3)

    fig.tight_layout()
    out_path = Path("results/figs/fig_phase_diagram.png")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200)
    plt.close(fig)

    Path("results/mechanism.json").write_text(json.dumps(out, indent=2))

    # ---- LaTeX macros for the papers -------------------------------- #
    macros = ["%% AUTO-GENERATED by scripts/analyze_mechanism.py -- do not edit"]
    if "vision" in out and "cap32" in out["vision"]:
        v = out["vision"]["cap32"]
        idx = {r: i for i, r in enumerate(v["ratios"])}
        macros += [
            f"\\newcommand{{\\mixRescueFinal}}{{{v['final_success'][idx[0.25]]:.2f}}}",
            f"\\newcommand{{\\mixHalfFinal}}{{{v['final_success'][idx[0.5]]:.2f}}}",
            f"\\newcommand{{\\mixOneFinal}}{{{v['final_success'][idx[1.0]]:.2f}}}",
            f"\\newcommand{{\\mixBlindFinal}}{{{v['final_success'][idx['unbounded']]:.2f}}}",
            f"\\newcommand{{\\mixRescueGain}}{{{v['final_success'][idx[0.25]] - v['final_success'][idx['unbounded']]:.2f}}}",
        ]
    if "contact" in out and "cap32" in out["contact"]:
        c = out["contact"]["cap32"]
        idx = {r: i for i, r in enumerate(c["ratios"])}
        macros += [
            f"\\newcommand{{\\contactMixFinal}}{{{c['final_success'][idx[0.25]]:.2f}}}",
            f"\\newcommand{{\\contactBlindFinal}}{{{c['final_success'][idx['unbounded']]:.2f}}}",
        ]
    (Path("paper/generated/mechanism.tex")).write_text("\n".join(macros) + "\n")
    print(f"wrote {out_path} + results/mechanism.json + paper/generated/mechanism.tex")


if __name__ == "__main__":
    main()
